# Generated by Django 5.1.4 on 2025-09-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productotienda',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos_tienda/'),
        ),
        migrations.AddField(
            model_name='productotienda',
            name='tipo',
            field=models.CharField(choices=[('PRODUCTO', 'Producto'), ('SERVICIO', 'Servicio')], default='PRODUCTO', max_length=15),
        ),
        migrations.AlterField(
            model_name='productotienda',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
