# Generated by Django 5.1.4 on 2025-12-02 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_storeordersellerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_conductor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('TIENDA', 'Tienda'), ('CLIENTE', 'Cliente'), ('CONDUCTOR', 'Conductor')], default='CLIENTE', max_length=10),
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licencia_numero', models.CharField(blank=True, max_length=64, null=True)),
                ('vehiculo_tipo', models.CharField(blank=True, choices=[('auto', 'Auto'), ('moto', 'Moto'), ('bici', 'Bicicleta')], max_length=20, null=True)),
                ('vehiculo_placa', models.CharField(blank=True, max_length=20, null=True)),
                ('vehiculo_color', models.CharField(blank=True, max_length=30, null=True)),
                ('capacidad_paquetes', models.PositiveSmallIntegerField(default=1, help_text='Capacidad de paquetes o pasajeros permitidos.')),
                ('estado', models.CharField(choices=[('offline', 'Fuera de línea'), ('available', 'Disponible'), ('on_trip', 'En viaje')], default='offline', max_length=20)),
                ('ubicacion_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ubicacion_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_conductor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('taxi', 'Taxi'), ('delivery', 'Delivery')], max_length=20)),
                ('pickup_direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('dropoff_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('assigned', 'Asignado'), ('in_progress', 'En curso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('distancia_metros', models.PositiveIntegerField(blank=True, null=True)),
                ('duracion_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ruta_geojson', models.JSONField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('asignado_en', models.DateTimeField(blank=True, null=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cliente', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'es_conductor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_conductor', to=settings.AUTH_USER_MODEL)),
                ('store_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='store.storeorder')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
