# Generated by Django 5.1.4 on 2025-12-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_categoria_tipo_productotienda_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
    ]
