# Generated by Django 5.1.4 on 2026-07-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_passwordresetcode'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='store_messa_convers_555ae4_idx',
            old_name='store_messa_convers_idx',
        ),
        migrations.RenameIndex(
            model_name='tasacambio',
            new_name='store_tasac_creado_cff2f1_idx',
            old_name='store_tasac_creado_idx',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='cedula_foto_frente',
            field=models.ImageField(blank=True, null=True, upload_to='conductores/cedulas/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='cedula_foto_reverso',
            field=models.ImageField(blank=True, null=True, upload_to='conductores/cedulas/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='licencia_foto',
            field=models.ImageField(blank=True, null=True, upload_to='conductores/licencias/'),
        ),
    ]
