# Generated by Django 5.1.4 on 2026-07-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_rename_store_messa_convers_idx_store_messa_convers_555ae4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='codigo_entrega',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='estado',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('assigned', 'Asignado'), ('arrived_pickup', 'Llegó al punto de recogida'), ('in_progress', 'En curso'), ('arrived_dropoff', 'Llegó al destino'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
    ]
