# Generated by Django 5.1.4 on 2026-07-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_servicerequest_codigo_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productotienda',
            name='imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to='productos_tienda/'),
        ),
        migrations.AddField(
            model_name='productotienda',
            name='imagen_3',
            field=models.ImageField(blank=True, null=True, upload_to='productos_tienda/'),
        ),
        migrations.AddField(
            model_name='productotienda',
            name='permite_encargo',
            field=models.BooleanField(default=False, help_text='Permite recibir pedidos aunque el stock disponible sea insuficiente (venta por encargo).'),
        ),
    ]
