# Generated by Django 5.1.4 on 2026-07-08 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_productotienda_imagen_2_productotienda_imagen_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='pago_movil_banco',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='pago_movil_cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='pago_movil_telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('pago_movil', 'Pago móvil'), ('efectivo', 'Efectivo'), ('zelle', 'Zelle')], max_length=15)),
                ('referencia', models.CharField(blank=True, max_length=40, null=True)),
                ('captura', models.ImageField(blank=True, null=True, upload_to='pagos/')),
                ('estado', models.CharField(choices=[('reported', 'Reportado'), ('confirmed', 'Confirmado'), ('rejected', 'Rechazado')], default='reported', max_length=15)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='store.storeorder')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
