# Generated by Django 5.1.4 on 2026-07-08 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_tienda_pago_movil_banco_tienda_pago_movil_cedula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.storeorder')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store.productotienda')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
