"""
Django settings for backend_ojeda project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from decouple import Csv, config
import os
from urllib.parse import unquote, urlparse


from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def clean_env_list(values):
    return [value.strip() for value in values if value and value.strip()]


def first_env_value(*names, default=''):
    for name in names:
        value = config(name, default='')
        if isinstance(value, str):
            value = value.strip()
        if value:
            return value
    return default


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY', default='django-insecure-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DJANGO_DEBUG', default=True, cast=bool)

default_allowed_hosts = ['0.0.0.0', 'localhost', '127.0.0.1']
ALLOWED_HOSTS = config(
    'DJANGO_ALLOWED_HOSTS',
    default=','.join(default_allowed_hosts),
    cast=Csv(),
)
ALLOWED_HOSTS = clean_env_list(ALLOWED_HOSTS)

railway_public_domain = config('RAILWAY_PUBLIC_DOMAIN', default='').strip()
if railway_public_domain:
    ALLOWED_HOSTS.append(railway_public_domain)

CSRF_TRUSTED_ORIGINS = [
    # Permite acceder vía túneles de ngrok sin disparar el chequeo de origen
    'https://*.ngrok-free.app',
    # Permite subdominios temporales de Cloudflare Tunnel
    'https://*.trycloudflare.com',
]
CSRF_TRUSTED_ORIGINS.extend(
    clean_env_list(config('DJANGO_CSRF_TRUSTED_ORIGINS', default='', cast=Csv()))
)
if railway_public_domain:
    CSRF_TRUSTED_ORIGINS.append(f'https://{railway_public_domain}')

MAPBOX_ACCESS_TOKEN = config('MAPBOX_TOKEN', default=None)
GOOGLE_WEB_CLIENT_ID = config('GOOGLE_WEB_CLIENT_ID', default='')


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'graphene_django',
    'drf_spectacular',
    'drf_yasg',
    'rest_framework_swagger',
    'rest_framework_simplejwt',
    'rest_framework',
    'storages',
    'store',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend_ojeda.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_ojeda.wsgi.application'
ASGI_APPLICATION = 'backend_ojeda.asgi.application'

# Channels: por defecto usa la capa en memoria (suficiente para un único
# proceso en desarrollo). Si se define ``REDIS_URL`` se conmuta a redis.
REDIS_URL = config('REDIS_URL', default=None)
if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {'BACKEND': 'channels.layers.InMemoryChannelLayer'},
    }

EXPO_PUSH_DISABLED = config('EXPO_PUSH_DISABLED', default=False, cast=bool)


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


def postgres_database_config():
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('POSTGRES_DB', default=config('PGDATABASE', default='mydatabase')),
        'USER': config('POSTGRES_USER', default=config('PGUSER', default='myuser')),
        'PASSWORD': config('POSTGRES_PASSWORD', default=config('PGPASSWORD', default='mypassword')),
        'HOST': config('POSTGRES_HOST', default=config('PGHOST', default='localhost')),
        'PORT': config('POSTGRES_PORT', default=config('PGPORT', default=5432), cast=int),
        'CONN_MAX_AGE': config('DJANGO_DB_CONN_MAX_AGE', default=60, cast=int),
    }


def database_config_from_url(database_url):
    parsed = urlparse(database_url)
    if parsed.scheme not in {'postgres', 'postgresql'}:
        raise ValueError(f'Unsupported DATABASE_URL scheme: {parsed.scheme}')

    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': parsed.path.lstrip('/'),
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or 'localhost',
        'PORT': parsed.port or 5432,
        'CONN_MAX_AGE': config('DJANGO_DB_CONN_MAX_AGE', default=60, cast=int),
    }


DATABASE_URL = config('DATABASE_URL', default='').strip()
DB_ENGINE = config('DJANGO_DB_ENGINE', default='sqlite').strip().lower()
postgres_requested = DB_ENGINE == 'postgresql' or bool(
    config('POSTGRES_HOST', default='').strip() or config('PGHOST', default='').strip()
)

if DATABASE_URL:
    DATABASES = {'default': database_config_from_url(DATABASE_URL)}
elif postgres_requested:
    DATABASES = {'default': postgres_database_config()}
else:  # Por defecto, usa SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / config('DJANGO_DB_NAME', default='db.sqlite3'),
        }
    }

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': 'mydatabase',  # Mismo valor que en docker-compose.yml
#        'USER': 'myuser',       # Mismo valor que en docker-compose.yml
#        'PASSWORD': 'mypassword',  # Mismo valor que en docker-compose.yml
#        'HOST': 'db',           # Nombre del servicio del contenedor en docker-compose.yml
#        'PORT': 5432,           # Puerto por defecto de PostgreSQL
#    }
#}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

REST_FRAMEWORK = {

     'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Ojeda Backend API',
    'DESCRIPTION': (
        'Documentacion interactiva del backend.\n\n'
        'Autenticacion:\n'
        '- Obtiene un JWT en `/api/token/`.\n'
        '- En Swagger usa el boton `Authorize` con `Bearer <token>`.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
    'SERVE_AUTHENTICATION': [],
    'COMPONENT_SPLIT_REQUEST': True,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'displayRequestDuration': True,
        'persistAuthorization': True,
    },
    'SECURITY': [{'BearerAuth': []}],
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    },
}

AUTH_USER_MODEL = 'store.Usuario'  # Asegúrate de que esto esté configurado


GRAPHENE = {
    'SCHEMA': 'backend_ojeda.schema.schema',
}


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = config('DJANGO_TIME_ZONE', default='UTC')

USE_I18N = True

USE_TZ = True

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / "staticfiles"

STATIC_URL = '/static/'
MEDIA_BUCKET_NAME = first_env_value('AWS_STORAGE_BUCKET_NAME', 'BUCKET')
MEDIA_BUCKET_ACCESS_KEY = first_env_value('AWS_ACCESS_KEY_ID', 'ACCESS_KEY_ID')
MEDIA_BUCKET_SECRET_KEY = first_env_value('AWS_SECRET_ACCESS_KEY', 'SECRET_ACCESS_KEY')
MEDIA_BUCKET_ENDPOINT = first_env_value('AWS_S3_ENDPOINT_URL', 'ENDPOINT')
MEDIA_BUCKET_REGION = first_env_value('AWS_S3_REGION_NAME', 'REGION', default='auto')
MEDIA_BUCKET_LOCATION = first_env_value('AWS_MEDIA_LOCATION', default='media')
MEDIA_BUCKET_ADDRESSING_STYLE = first_env_value('AWS_S3_ADDRESSING_STYLE', default='virtual')
S3_MEDIA_ENABLED = config(
    'S3_MEDIA_ENABLED',
    default='true'
    if MEDIA_BUCKET_NAME and MEDIA_BUCKET_ENDPOINT and MEDIA_BUCKET_ACCESS_KEY and MEDIA_BUCKET_SECRET_KEY
    else 'false',
    cast=bool,
)

if S3_MEDIA_ENABLED:
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3.S3Storage',
            'OPTIONS': {
                'bucket_name': MEDIA_BUCKET_NAME,
                'access_key': MEDIA_BUCKET_ACCESS_KEY,
                'secret_key': MEDIA_BUCKET_SECRET_KEY,
                'endpoint_url': MEDIA_BUCKET_ENDPOINT,
                'region_name': MEDIA_BUCKET_REGION,
                'default_acl': None,
                'querystring_auth': config('AWS_QUERYSTRING_AUTH', default=True, cast=bool),
                'querystring_expire': config('AWS_QUERYSTRING_EXPIRE', default=3600, cast=int),
                'file_overwrite': config('AWS_S3_FILE_OVERWRITE', default=False, cast=bool),
                'location': MEDIA_BUCKET_LOCATION.strip('/'),
                'addressing_style': MEDIA_BUCKET_ADDRESSING_STYLE or None,
            },
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }
    MEDIA_URL = config('DJANGO_MEDIA_URL', default='/media/')
    MEDIA_ROOT = BASE_DIR / 'media'
    SERVE_MEDIA = False
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }
    MEDIA_URL = '/media/'
    MEDIA_ROOT = Path(config('DJANGO_MEDIA_ROOT', default=str(BASE_DIR / 'media')))
    SERVE_MEDIA = config('DJANGO_SERVE_MEDIA', default=DEBUG, cast=bool)

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
