"""
Django settings for backend_ojeda project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from decouple import config
import os


from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8a_h)l=(3^qv&ux^7mh#ckvfcy*1q0^55s3qmul*x25l8j*01+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

ALLOWED_HOSTS = [
    '0.0.0.0', 
    'localhost',
    '127.0.0.1',
    "backend-ojeda-app.onrender.com",
    ".onrender.com",
    "localhost", "127.0.0.1",
    "*"
    ]

CSRF_TRUSTED_ORIGINS = [
    "https://backend-ojeda-app.onrender.com",
    "https://*.onrender.com",
]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_spectacular',
    'drf_yasg',
    'rest_framework_swagger',
    'rest_framework_simplejwt',
    'rest_framework',
    'store',
    'graphene_django',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.apple',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'channels',
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

SITE_ID = 1

ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = 'none' # Can be set to 'mandatory' or 'optional'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    },
    'apple': {
        'SCOPE': [
            'name',
            'email'
        ],
        'LOGIN_PARAMS': { # Optional: Custom parameters for the authorization URL
            'response_mode': 'form_post', # Or 'fragment' or 'query'
        },
        # You will need to configure your Apple App ID, Services ID, Team ID, Key ID, and private key
        # 'APP': {
        #    'client_id': 'your.service.id', # Services ID
        #    'secret': 'YOUR_APPLE_PRIVATE_KEY_CONTENT_HERE', # Content of your .p8 key file
        #    'key': 'YOUR_APPLE_KEY_ID', # Key ID
        #    'certificate_key': None, # Or path to your .pem certificate if not using .p8
        #    'team_id': 'YOUR_APPLE_TEAM_ID'
        # }
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend_ojeda.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_ojeda.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DB_ENGINE = config('DJANGO_DB_ENGINE', default='sqlite')

if DB_ENGINE == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('POSTGRES_DB', default='mydatabase'),
            'USER': config('POSTGRES_USER', default='myuser'),
            'PASSWORD': config('POSTGRES_PASSWORD', default='mypassword'),
            'HOST': config('POSTGRES_HOST', default='localhost'),
            'PORT': config('POSTGRES_PORT', default=5432),
        }
    }
else:  # Por defecto, usa SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / config('DJANGO_DB_NAME', default='db.sqlite3'),
        }
    }

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': 'mydatabase',  # Mismo valor que en docker-compose.yml
#        'USER': 'myuser',       # Mismo valor que en docker-compose.yml
#        'PASSWORD': 'mypassword',  # Mismo valor que en docker-compose.yml
#        'HOST': 'db',           # Nombre del servicio del contenedor en docker-compose.yml
#        'PORT': 5432,           # Puerto por defecto de PostgreSQL
#    }
#}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

REST_FRAMEWORK = {

     'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'USE_JWT': True, # dj-rest-auth uses JWTs for authentication
}

REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_HTTPONLY': False, # Allow JWT to be accessed by JavaScript
    'TOKEN_MODEL': None, # We are using JWTs, not DRF's Token model via dj_rest_auth
}

AUTH_USER_MODEL = 'store.Usuario'  # Asegúrate de que esto esté configurado


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / "staticfiles"

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

GRAPHENE = {
    'SCHEMA': 'backend_ojeda.schema.schema'
}

ASGI_APPLICATION = 'backend_ojeda.asgi.application'

# Stripe API Keys
STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY', default='your_stripe_publishable_key')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='your_stripe_secret_key')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='your_stripe_webhook_secret') # For webhook verification

# Binance API Keys (ensure these are for Binance Pay, not trading, if different)
BINANCE_API_KEY = config('BINANCE_API_KEY', default='your_binance_api_key')
BINANCE_SECRET_KEY = config('BINANCE_SECRET_KEY', default='your_binance_secret_key')
# Depending on the Binance Pay API, you might need a merchant ID or other specific configs
BINANCE_MERCHANT_ID = config('BINANCE_MERCHANT_ID', default='your_binance_merchant_id')
BINANCE_PAY_BASE_URL = config('BINANCE_PAY_BASE_URL', default='https://bpay.binanceapi.com') # Example, verify actual
